description: |
  Provider configuration object.

  This will vary depending on the provider.
required: true
content:
  application/json:
    schema:
      $ref: '../schemas/ProviderConfigurationOptions.yaml'
