description: |
  Provider configuration object.

  This will vary depending on the provider.
required: true
content:
  application/json:
    schema:
      type: object
      properties:
        configuration:
          oneOf:
            - $ref: '../providers/DemoProvider.yaml#/Configuration'
            - $ref: '../providers/Antech.yaml#/Configuration'
            - $ref: '../providers/Idexx.yaml#/Configuration'
            - $ref: '../providers/Zoetis.yaml#/Configuration'
