apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  annotations:
    description: The broker's MQTT port.
spec:
  selector:
    app: activemq
  ports:
    - port: 1883
      targetPort: 1883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: data
              mountPath: /opt/activemq/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: activemq-pvc
