apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmi-api
  template:
    metadata:
      labels:
        app: dmi-api
    spec:
      containers:
        - name: dmi-api
          image: dmi-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: JWT_SECRET_KEY
              value: 'platano maduro'
            - name: SECRET_KEY
              value: 'To@i#q2Z5!pStQTN9HxVocWHg9YH56f^'
            - name: DATABASE_HOST
              value: 'mysql'
            - name: DATABASE_DATABASE
              value: 'diagnostic-modality-integration'
            - name: DATABASE_USERNAME
              value: 'root'
            - name: DATABASE_PASSWORD
              value: 'Asdf1234'
            - name: DATABASE_SYNCHRONIZE
              value: 'true'
            - name: MONGO_URI
              value: 'mongodb://mongo/diagnostic-modality-integration'
            - name: ACTIVEMQ_HOSTNAME
              value: 'activemq'

