version: '3.9'

services:
  api:
    image: 216821345641.dkr.ecr.us-east-1.amazonaws.com/dmi-api:latest
    ports:
      - '3000:3000'
    volumes:
      - ./containers/dmi-api/logs:/app/logs
    depends_on:
      - mysql
      - mongo
      - activemq
    env_file: .env
    environment:
      PORT: '3000'
      DATABASE_HOST: 'mysql'
      MONGO_URI: 'mongodb://mongo/diagnostic-modality-integration'
      ACTIVEMQ_HOSTNAME: 'activemq'
    command: ['./scripts/wait-for-all.sh', 'npm run start:prod']
  engine:
    image: dmi-engine_engine:latest
    ports:
      - '4000:4000'
    volumes:
      - ./containers/dmi-engine/logs:/app/logs
    depends_on:
      - activemq
      - redis
    environment:
      PORT: '4000'
      MQTT_HOST: 'activemq'
      MQTT_PORT: '1883'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    command: ['./scripts/wait-for-all.sh', 'npm run start:prod']
  mongo:
    image: mongo:3.6
    volumes:
      - ./containers/mongo/data:/data/db
    ports:
      - '27017:27017'
  mysql:
    image: mysql:8
    env_file: .env
    volumes:
      - ./containers/mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
  activemq:
    image: rmohr/activemq
    env_file: .env
    volumes:
      - ./containers/activemq/data:/opt/activemq/data
      - ./containers/activemq/conf:/opt/activemq/conf
    ports:
      - '1883:1883'
      - '8161:8161'
  redis:
    image: redis
    ports:
      - '6379:6379'
