apiVersion: v1
kind: Service
metadata:
  name: demo-provider-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4500
  selector:
    name: demo-provider-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-provider-api
spec:
  selector:
    matchLabels:
      name: demo-provider-api
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-provider-api
    spec:
      containers:
        - name: demo-provider-api
          image: nominaldevacr.azurecr.io/demo-provider-api:3fdeb2a7183889c32e5eed9a5fee929f6bd95985
          imagePullPolicy: Always
          ports:
            - containerPort: 4500
          env:
            - name: PORT
              value: '4500'
            - name: DATABASE_TYPE
              value: 'mysql'
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: dmi-config
                  key: DATABASE_HOST
            - name: DATABASE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dmi-config
                  key: DEMO_PROVIDER_DATABASE
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dmi-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dmi-config
                  key: DATABASE_PASSWORD
            - name: DATABASE_SYNCHRONIZE
              value: 'false'
