name: Deploy Demo Provider API to AKS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ demo-provider-api-updated ]

env:
  APP_NAME: demo-provider-api
  AZURE_RG: dmi-rg_app-dev
  ACR_REGISTRY: nominaldevacr
  AKS_CLUSTER_NAME: dmi-cluster-dev
  SHA: d06255b4ecd875f55c376cf5315a8209c7009a58

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - uses: azure/aks-set-context@v2
        with:
          resource-group: ${{ env.AZURE_RG }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
            kubernetes/dmi-dev/demo-provider-api.yaml
          images: |
            ${{ env.ACR_REGISTRY }}.azurecr.io/${{ env.APP_NAME }}:${{ env.SHA }}
