name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: bundle -t yaml -o dmi-api-$RELEASE_VERSION.yaml reference/dmi.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dmi-api-${{ env.RELEASE_VERSION }}.yaml
