name: Create GitHub Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: bundle -t yaml -o dmi-api.yaml reference/dmi.yaml
      - name: Test
        run: cat dmi-api.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dmi-api.yaml
