name: Validate API Spec

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: validate reference/dmi.yaml
